### ISSUE TITLE
curious

### ISSUE THREAD

**Issue by jeacott** [erossignon/redmine-kanban-core#1]
Hi,
 I'm very curious about this project and would like to know what the current status is, and if/when it might be ready for use?

Kindest regards

**Comment by erossignon** [comment]
Hi
the project is working and is used by https://github.com/erossignon/kanbandashboard.

kanbandashboard is a  Node+Angular  application that build KANBAN Cumulative Flow Diagram ,calculates lead time , work in progress and velocities out  of a ongoing redmine project.
It can also evaluate ETA ( estimated time of arrival)  using the "yesterday weather" method.
